import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const handleCredentialResponse = (googleUser: any) => {
    console.log(googleUser);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="referrer" content="strict-origin-when-cross-origin" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://accounts.google.com/gsi/client"
        strategy="lazyOnload"
        onLoad={() => {
          console.log('google oAuth 2.0 library is loaded');
        }}
      ></Script>
      <main className={styles.main}>

        <div className={styles.center}>
          <div
            id="g_id_onload"
            data-client_id="3751517572-2cq5s87bos5c328nhj4p6drhp28uagmd.apps.googleusercontent.com"
            data-ux_mode="redirect"
            data-login_uri="https://www.example.com/your_login_endpoint"
          ></div>
          <div className="g_id_signin" data-type="standard"></div>
        </div>

        {/* <script src="https://accounts.google.com/gsi/client" async defer></script> */}
        {/* <div
          id="g_id_onload"
          data-client_id="3751517572-2cq5s87bos5c328nhj4p6drhp28uagmd.apps.googleusercontent.com"
          data-ux_mode="redirect"
          data-login_uri="https://www.example.com/your_login_endpoint"
        ></div>
        <div className="g_id_signin" data-type="standard"></div> */}

        {/* <div id="g_id_onload"
              data-client_id="3751517572-2cq5s87bos5c328nhj4p6drhp28uagmd.apps.googleusercontent.com"
              data-callback={handleCredentialResponse}>
        </div>
        <div className="g_id_signin" data-type="standard"></div> */}

        <div className={styles.grid}>
          Check 3rd party oAuth functionality
        </div>
      </main>
    </>
  )
}
